turnirv5/turnir_project/routes/routes.py
from flask import Blueprint, render_template, flash, request, jsonify, redirect, url_for, abort
from sqlalchemy import desc
from ..models.models import ParticipantsDB, FightsDB, CompetitionsDB, BacklogDB, RegistrationsDB
from ..extensions import db
import csv

home = Blueprint('home', __name__, template_folder='templates')


@home.route('/')
def home_view():
    return redirect(url_for('home.competition_start'))


@home.route('/fill_fighters')
def fill_fighters():
    with open('fighters.csv', encoding='utf8') as csvfile:
        fighters_csv_list = csv.reader(csvfile)

        for row in fighters_csv_list:
            new_fighter = ParticipantsDB(participant_first_name=row[0], participant_last_name=row[1], fighter_image = row[8])
            db.session.add(new_fighter)
            try:
                db.session.commit()
                print("Боец импортирован в ParticipantsDB")
            except Exception as e:
                print("Не получилось импортировать бойцов. Ошибка: ", e)
                db.session.rollback()
    return "результат импорта - в принт"


def fight_create_func(competition_id, round_number, final_status):
    competition_id = competition_id
    round_number = round_number
    final_status = final_status
    backlog_data = BacklogDB.query.filter_by(competition_id=competition_id, round_number=round_number).all()
    red_fighter_id = backlog_data[0].fighter_id
    blue_fighter_id = backlog_data[1].fighter_id
    new_fight = FightsDB(competition_id=competition_id, round_number=round_number, red_fighter_id=red_fighter_id,
                         blue_fighter_id=blue_fighter_id, final_status=final_status)
    db.session.add(new_fight)

    try:
        db.session.commit()
        print("создан новый бой в круге №", round_number, ". id бойцов:", red_fighter_id, " и ", blue_fighter_id)

    except Exception as e:
        print("не получилось создать новый бой. Ошибка:  ", e)
        db.session.rollback()

    return round_number

    ################################################################


def delete_backlog_records(competition_id, round_number):
    competition_id = competition_id
    round_number = round_number
    # удаляем из бэклога записи с бойцами из созданннного боя
    last_created_fight = FightsDB.query.filter_by(competition_id=competition_id, round_number=round_number).order_by(
        desc(FightsDB.fight_id)).first()
    # удаляем записи из бэклога бойцов, которые зашли в бой
    backlog_record_to_delete_red = BacklogDB.query.filter_by(competition_id=competition_id, round_number=round_number,
                                                             fighter_id=last_created_fight.red_fighter_id).order_by(
        desc(BacklogDB.fighter_id)).first()
    if backlog_record_to_delete_red is None:
        abort(404, description="No backlog record was Found with the given ID")
    else:
        db.session.delete(backlog_record_to_delete_red)
    backlog_record_to_delete_blue = BacklogDB.query.filter_by(competition_id=competition_id, round_number=round_number,
                                                              fighter_id=last_created_fight.blue_fighter_id).order_by(
        desc(BacklogDB.fighter_id)).first()
    if backlog_record_to_delete_blue is None:
        abort(404, description="No backlog record was Found with the given ID")
    else:
        db.session.delete(backlog_record_to_delete_blue)
    try:
        db.session.commit()
        print("удалены записи из бэклога. red_fighter: ", backlog_record_to_delete_red, ". blue_fighter: ",
              backlog_record_to_delete_blue)
    except Exception as e:
        print("Не удалось удалить записи из бэклога", e)
        db.session.rollback()
    ########################################################


@home.route('/competition_start/')
def competition_start():
    # создаем первый бой
    # fight_create_func(1)
    # last_created_fight = FightsDB.query.order_by(desc(FightsDB.fight_id)).first()
    return render_template('competition_start.html')


@home.route('/competition_create_new/')
def competition_create_new():
    # удаляем все из бэклога, если там что-то есть
    db.session.query(BacklogDB).delete()
    db.session.commit()
    #  создаем новое соревнование
    new_competition = CompetitionsDB()
    db.session.add(new_competition)

    try:
        db.session.commit()
        created_competition_data = CompetitionsDB.query.order_by(desc(CompetitionsDB.competition_id)).first()
        competition_id = created_competition_data.competition_id
        # создаем записи регистраций на созданное соревнование
        participant_data = ParticipantsDB.query.all()
        for participant in participant_data:
            new_registration = RegistrationsDB(participant_id=participant.participant_id, competition_id=competition_id,
                                               activity_status=1)
            db.session.add(new_registration)
            try:
                db.session.commit()
            except Exception as e:
                print("Не удалось создать запись в регистрациях", e)
                db.session.rollback()

        # помещаем всех бойцов в бэклог
        # participants_data = ParticipantsDB.query.all()
        regs_data = RegistrationsDB.query.filter_by(competition_id=competition_id).all()
        for registration in regs_data:
            reg_id = registration.reg_id
            new_backlog_record = BacklogDB(fighter_id=reg_id, competition_id=competition_id, round_number=1)
            db.session.add(new_backlog_record)
            try:
                db.session.commit()
            except Exception as e:
                print("Не удалось создать запись в бэклоге", e)
                db.session.rollback()

        # проверяем ситуацию в бэклоге в текущем и следующем раунде
        current_backlog_data = BacklogDB.query.filter_by(competition_id=competition_id, round_number=1).all()
        next_round_backlog_data = BacklogDB.query.filter_by(competition_id=competition_id, round_number=2).all()
        print("comp_start: длина бэклога следующего раунда: ", len(next_round_backlog_data),
              "длина бэклога текущего раунда: ", len(current_backlog_data))
        # ситуация №1 в текущем раунде нет боев, а в следующем раунде есть два бойца в бэклоге. Значит следующий бой будет финальным. 

        if len(current_backlog_data) == 0 and len(next_round_backlog_data) == 2:

            current_round_number = 2

            final_status = 'not'
            fight_create_func(competition_id, current_round_number, final_status)
            # удаляем из бэклога записи с бойцами
            delete_backlog_records(competition_id, current_round_number)
        # ситуация №2. Если в текущем раунде два бойца, а в следующем ноль. это тоже будет финальный бой
        elif len(current_backlog_data) == 2 and len(next_round_backlog_data) == 0:

            current_round_number = 1
            final_status = 'not'
            fight_create_func(competition_id, current_round_number, final_status)
            # удаляем из бэклога записи с бойцами
            delete_backlog_records(competition_id, current_round_number)
        # ситуация №3. Если в текущем раунде один боец, а в следующем тоже один боец. то это тоже будет финальный бой
        elif len(current_backlog_data) == 1 and len(next_round_backlog_data) == 1:

            current_round_number = 1
            final_status = 'not'
            next_round_fighter_data = BacklogDB.query.filter_by(competition_id=competition_id,
                                                                round_number=current_round_number + 1).first()
            # проверяем на случай если это один и тот же боец
            current_round_fighter_data = BacklogDB.query.filter_by(competition_id=competition_id,
                                                                   round_number=current_round_number).first()
            if next_round_fighter_data.fighter_id != current_round_fighter_data.fighter_id:
                next_round_fighter_data.round_number = current_round_number
                try:
                    db.session.commit()
                    print("изменили данные бойца из следующего круга")
                except Exception as e:
                    print("не удалось переписать номер круга в записи бойца из следующего круга", e)
                    db.session.rollback()

            fight_create_func(competition_id, current_round_number, final_status)
            # удаляем из бэклога записи с бойцами
            delete_backlog_records(competition_id, current_round_number)
        else:
            fight_create_func(competition_id, 1, 'not')
            # удаляем из бэклога записи с созданным боем
            last_created_fight = FightsDB.query.filter_by(competition_id=competition_id).order_by(
                desc(FightsDB.fight_id)).first()
            # удаляем записи из бэклога бойцов, которые зашли в бой
            delete_backlog_records(last_created_fight.competition_id, 1)

        return redirect(url_for('home.competition_view', competition_id=competition_id))

    except Exception as e:
        print("Не удалось создать соревнование", e)
        db.session.rollback()
        return render_template('competition_start.html')


@home.route('/finish/<int:fight_id>')
def test(fight_id):
    print("fight_id_test", fight_id)
    return "testtt"


@home.route('/competition/<int:competition_id>')
def competition_view(competition_id):
    competition_id = competition_id
    # round_number = fight_create_func(round_number_prev)
    last_created_fight = FightsDB.query.filter_by(competition_id=competition_id).order_by(
        desc(FightsDB.fight_id)).first()
    print("id последнего созданного боя", last_created_fight.fight_id)
    return render_template("competition.html", fight_data=last_created_fight)


@home.route('/competition_finish/<int:fight_id>')
def finish_red(fight_id):
    fight_data = FightsDB.query.get(fight_id)

turnirv5/turnir_project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
{% block head %}
    <meta charset="UTF-8">


    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.css">

{% endblock %}
<title>{% block title %}  {% endblock %}</title>
</head>
<body>
   


    <div id="content">
        {% block content %}
        {% endblock %}
    </div> <!-- Это конец блока Content-->

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
<script>
    $(document).ready(function () {
        
    })
</script>

</body>
</html>

turnirv5/turnir_project/templates/competition.html
{% extends "base.html" %}

{% block content %}

<div class="container" style="margin-top: 10px">
  <div class="row">
    <div class="col text-center">
      <div class="title_data_div">
          <h3>Раунд: {{ fight_data.round_number }} </h3>
        <p data-id='{{fight_data.final_status}}' class="check_final_status"></p>
        <p data-id='{{fight_data.fight_id}}' class="check_fight_id"></p>
      </div>
    </div>
  </div>
  
  <div class="row">
    <div class="col text-center d-flex justify-content-end">
      <div class="red_fighter_div">
                    {{fight_data.red_fighter.registration_participant.participant_first_name}} {{fight_data.red_fighter.registration_participant.participant_last_name}}
                    <div style="margin-bottom: 180px;">
                            <img src= {{ fight_data.red_fighter.registration_participant.fighter_image }} class="float-left" alt="Fighter image" width="150" height="150">
                    </div>
        <p></p>
        <button data-id='{{fight_data.fight_id}}' type="button" class="select_red_fighter btn btn-primary">Выбрать</button>
      </div>  
      <p></p>

    </div>
    <div class="col text-center d-flex justify-content-start">
      <div class="blue_fighter_div">
            {{fight_data.blue_fighter.registration_participant.participant_first_name}} {{fight_data.blue_fighter.registration_participant.participant_last_name}}
            <div style="margin-bottom: 180px;">
                    <img src= {{ fight_data.blue_fighter.registration_participant.fighter_image }} class="float-left" alt="Fighter image" width="150" height="150">
            </div>
            <p></p>
            <button data-id='{{fight_data.fight_id}}' type="button" class="select_blue_fighter btn btn-primary">Выбрать</button>
      </div>

    </div>
    
  </div>
</div>          






<script src="https://code.jquery.com/jquery-3.5.1.js"></script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"></script>

<script>
    $(document).ready(function() {

      // Обработка нажатия красного бойца в ajax
      $(".red_fighter_div").click('.select_red_fighter_ajax', function(){
        //var fight_id = $(this).data('id');
        var fight_id = $('#ajax_red_button').data('id');

        console.log("fight_id c ajax кнопки: ", fight_id)

        $.ajax({
        url: '/ajaxfile',
        type: 'post',
        data: {fight_id:fight_id, winner_color:"red"},
        success: function(response){
            var final_status = response.final_status;
            var fight_id_response = response.fight_id;

            route_concat = "/competition_finish/"+ fight_id_response


            if (final_status == "finish") {
                  window.location.href=route_concat;
            }
            $('.red_fighter_div').html(response);
            $('.red_fighter_div').append(response.htmlresponsered);
            $('.blue_fighter_div').html(response);
            $('.blue_fighter_div').append(response.htmlresponseblue);
            $('.title_data_div').html(response);
            $('.title_data_div').append(response.htmlresponsetitle);

          }
        });

       });

      $('.select_red_fighter').click(function(){
        var fight_id = $(this).data('id');
        console.log("fight_id c первой кнопки: ", fight_id)
        $.ajax({
        url: '/ajaxfile',
        type: 'post',
        data: {fight_id:fight_id, winner_color:"red"},
        success: function(response){
            var final_status = response.final_status;
            var fight_id_response = response.fight_id;
            route_concat = "/competition_finish/"+ fight_id_response

            if (final_status == "finish") {
                  window.location.href=route_concat;
            }

            $('.red_fighter_div').html(response);
            $('.red_fighter_div').append(response.htmlresponsered);
            $('.blue_fighter_div').html(response);
            $('.blue_fighter_div').append(response.htmlresponseblue);
            $('.title_data_div').html(response);
            $('.title_data_div').append(response.htmlresponsetitle);

          }
        });
        });

        $('.select_blue_fighter').click(function(){
        var fight_id = $(this).data('id');
        //console.log("fight_id c первой кнопки: ", fight_id)
        $.ajax({
        url: '/ajaxfile',
        type: 'post',
        data: {fight_id:fight_id, winner_color:"blue"},
        success: function(response){
            var final_status = response.final_status;
            var fight_id_response = response.fight_id;
            route_concat = "/competition_finish/"+ fight_id_response

            if (final_status == "finish") {
                  window.location.href=route_concat;
            }

            $('.red_fighter_div').html(response);
            $('.red_fighter_div').append(response.htmlresponsered);
            $('.blue_fighter_div').html(response);
            $('.blue_fighter_div').append(response.htmlresponseblue);
            $('.title_data_div').html(response);
            $('.title_data_div').append(response.htmlresponsetitle);

          }
        });
        });

        $('.select_red_fighter').click(function(){
        var fight_id = $(this).data('id');
        console.log("fight_id c первой кнопки: ", fight_id)
        $.ajax({
        url: '/ajaxfile',
        type: 'post',
        data: {fight_id:fight_id, winner_color:"red"},
        success: function(response){
            var final_status = response.final_status;
            var fight_id_response = response.fight_id;
            route_concat = "/competition_finish/"+ fight_id_response

            if (final_status == "finish") {
                  window.location.href=route_concat;
            }

            $('.red_fighter_div').html(response);
            $('.red_fighter_div').append(response.htmlresponsered);
            $('.blue_fighter_div').html(response);
            $('.blue_fighter_div').append(response.htmlresponseblue);
            $('.title_data_div').html(response);
            $('.title_data_div').append(response.htmlresponsetitle);

          }
        });
        });

        // Обработка нажатия синего бойца в ajax
      $(".blue_fighter_div").click('.select_blue_fighter_ajax', function(){

        var fight_id = $('#ajax_blue_button').data('id');

        console.log("fight_id c ajax кнопки: ", fight_id)

        $.ajax({
        url: '/ajaxfile',
        type: 'post',
        data: {fight_id:fight_id, winner_color:"blue"},
        success: function(response){
            var final_status = response.final_status;
            var fight_id_response = response.fight_id;

            route_concat = "/competition_finish/"+ fight_id_response


            if (final_status == "finish") {
                  window.location.href=route_concat;
            }
            $('.red_fighter_div').html(response);
            $('.red_fighter_div').append(response.htmlresponsered);
            $('.blue_fighter_div').html(response);
            $('.blue_fighter_div').append(response.htmlresponseblue);
            $('.title_data_div').html(response);
            $('.title_data_div').append(response.htmlresponsetitle);

          }
        });

       });
     

} );
</script>

{% endblock %}

turnirv5/turnir_project/templates/competition_start.html
{% extends "base.html" %}

{% block title %} Начать турнир {% endblock %}

{% block content %}
<div class="container-fluid" style="margin-top: 10px">
    <div class="row">
        <div class="col">
            <div class="text-center">
                <a href="{{url_for( 'home.competition_create_new' )}}"><button type="button" class="btn btn-outline-info">Начать турнир</button></a>


            </div>
        </div>
    </div>


</div>

{% endblock %}

turnirv5/turnir_project/templates/finish.html
{% extends "base.html" %}

{% block content %}

<div class="container" style="margin-top: 10px">
  <div class="row">
    <div class="col text-center d-flex justify-content-center">
      <div>
        <h2>Победил {{ winner_data.participant_first_name }} {{ winner_data.participant_last_name }}</h2>

          <div class="text-center" style="margin-bottom: 20px;">
                    <img src= {{ winner_data.fighter_image }} class="float-center" alt="Fighter image" width="150" height="150">
          </div>

          <h4>Результаты</h4>
          <ul class="list-group list-group-flush">
              {% for fight_data in fights_data %}

              <li class="list-group-item">Раунд  {{ fight_data.round_number }}. {{ fight_data.red_fighter.registration_participant.participant_first_name }} {{ fight_data.red_fighter.registration_participant.participant_last_name }} - {{ fight_data.blue_fighter.registration_participant.participant_first_name }} {{ fight_data.blue_fighter.registration_participant.participant_last_name }}. Победил {{ fight_data.winner_reg.registration_participant.participant_first_name }} {{ fight_data.winner_reg.registration_participant.participant_last_name }} </li>
               {% endfor %}
            </ul>
        
      </div>
    </div>
  </div>
</div>          


{% endblock %}

turnirv5/turnir_project/templates/home.html
{% extends "base.html" %}

{% block content %}
homepage
{% endblock %}

turnirv5/turnir_project/templates/response_blue_fighter_div.html
{{fight_data.blue_fighter.registration_participant.participant_first_name}} {{fight_data.blue_fighter.registration_participant.participant_last_name}}
<div style="margin-bottom: 180px;">
        <img src= {{ fight_data.blue_fighter.registration_participant.fighter_image }} class="float-left" alt="Fighter image" width="150" height="150">
</div>
<p></p>
<button data-id= {{fight_data.fight_id}} type="button" class="select_blue_fighter_ajax btn btn-primary" id="ajax_blue_button">Выбрать</button>

turnirv5/turnir_project/templates/response_red_fighter_div.html
{{fight_data.red_fighter.registration_participant.participant_first_name}} {{fight_data.red_fighter.registration_participant.participant_last_name}}
            <div style="margin-bottom: 180px;">
                    <img src= {{ fight_data.red_fighter.registration_participant.fighter_image }} class="float-left" alt="Fighter image" width="150" height="150">
            </div>
<p></p>
<button data-id= {{fight_data.fight_id}} type="button" class="select_red_fighter_ajax btn btn-primary" id="ajax_red_button">Выбрать</button>

turnirv5/turnir_project/templates/response_title_div.html
<h3>Раунд: {{ fight_data.round_number }} </h3>